#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : mdds
Version  : 2.1.1
Release  : 10
URL      : https://gitlab.com/mdds/mdds/-/archive/2.1.1/mdds-2.1.1.tar.gz
Source0  : https://gitlab.com/mdds/mdds/-/archive/2.1.1/mdds-2.1.1.tar.gz
Summary  : A collection of multi-dimensional data structure and indexing algorithm
Group    : Development/Tools
License  : MIT
Requires: mdds-license = %{version}-%{release}
BuildRequires : dejagnu
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Multi-Dimensional Data Structure (mdds)
=======================================
A collection of multi-dimensional data structure and indexing
algorithm.

%package dev
Summary: dev components for the mdds package.
Group: Development
Provides: mdds-devel = %{version}-%{release}
Requires: mdds = %{version}-%{release}

%description dev
dev components for the mdds package.


%package doc
Summary: doc components for the mdds package.
Group: Documentation

%description doc
doc components for the mdds package.


%package license
Summary: license components for the mdds package.
Group: Default

%description license
license components for the mdds package.


%prep
%setup -q -n mdds-2.1.1
cd %{_builddir}/mdds-2.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692643602
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1692643602
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mdds
cp %{_builddir}/mdds-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/mdds/9b284bb2e965bb644bd7945b4198c55020a2714a || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mdds-2.1/mdds/flat_segment_tree.hpp
/usr/include/mdds-2.1/mdds/flat_segment_tree_def.inl
/usr/include/mdds-2.1/mdds/flat_segment_tree_itr.hpp
/usr/include/mdds-2.1/mdds/global.hpp
/usr/include/mdds-2.1/mdds/multi_type_matrix.hpp
/usr/include/mdds-2.1/mdds/multi_type_matrix_def.inl
/usr/include/mdds-2.1/mdds/multi_type_vector.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/aos/block_util.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/aos/iterator.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/aos/main.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/aos/main_def.inl
/usr/include/mdds-2.1/mdds/multi_type_vector/block_funcs.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/collection.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/collection_def.inl
/usr/include/mdds-2.1/mdds/multi_type_vector/env.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/iterator_node.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/macro.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/soa/block_util.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/soa/iterator.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/soa/main.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/soa/main_def.inl
/usr/include/mdds-2.1/mdds/multi_type_vector/standard_element_blocks.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/types.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/types_util.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector/util.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector_itr.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector_macro.hpp
/usr/include/mdds-2.1/mdds/multi_type_vector_types.hpp
/usr/include/mdds-2.1/mdds/node.hpp
/usr/include/mdds-2.1/mdds/point_quad_tree.hpp
/usr/include/mdds-2.1/mdds/quad_node.hpp
/usr/include/mdds-2.1/mdds/ref_pair.hpp
/usr/include/mdds-2.1/mdds/rtree.hpp
/usr/include/mdds-2.1/mdds/rtree_def.inl
/usr/include/mdds-2.1/mdds/segment_tree.hpp
/usr/include/mdds-2.1/mdds/segment_tree_def.inl
/usr/include/mdds-2.1/mdds/sorted_string_map.hpp
/usr/include/mdds-2.1/mdds/sorted_string_map_def.inl
/usr/include/mdds-2.1/mdds/trie_map.hpp
/usr/include/mdds-2.1/mdds/trie_map_def.inl
/usr/include/mdds-2.1/mdds/trie_map_itr.hpp
/usr/lib64/pkgconfig/mdds-2.1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/mdds/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mdds/9b284bb2e965bb644bd7945b4198c55020a2714a
