#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mdds
Version  : 1.3.1
Release  : 1
URL      : https://gitlab.com/mdds/mdds/-/archive/1.3.1/mdds-1.3.1.tar.gz
Source0  : https://gitlab.com/mdds/mdds/-/archive/1.3.1/mdds-1.3.1.tar.gz
Summary  : A collection of multi-dimensional data structure and indexing algorithm
Group    : Development/Tools
License  : MIT
Requires: mdds-license
BuildRequires : boost-dev

%description
Multi-Dimensional Data Structure (mdds)
=======================================
A collection of multi-dimensional data structure and indexing
algorithm.

%package dev
Summary: dev components for the mdds package.
Group: Development
Provides: mdds-devel

%description dev
dev components for the mdds package.


%package doc
Summary: doc components for the mdds package.
Group: Documentation

%description doc
doc components for the mdds package.


%package license
Summary: license components for the mdds package.
Group: Default

%description license
license components for the mdds package.


%prep
%setup -q -n mdds-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534604259
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534604259
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mdds
cp LICENSE %{buildroot}/usr/share/doc/mdds/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mdds-1.2/mdds/flat_segment_tree.hpp
/usr/include/mdds-1.2/mdds/flat_segment_tree_def.inl
/usr/include/mdds-1.2/mdds/flat_segment_tree_itr.hpp
/usr/include/mdds-1.2/mdds/global.hpp
/usr/include/mdds-1.2/mdds/multi_type_matrix.hpp
/usr/include/mdds-1.2/mdds/multi_type_matrix_def.inl
/usr/include/mdds-1.2/mdds/multi_type_vector.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector/collection.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector/collection_def.inl
/usr/include/mdds-1.2/mdds/multi_type_vector_custom_func1.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector_custom_func2.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector_custom_func3.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector_def.inl
/usr/include/mdds-1.2/mdds/multi_type_vector_itr.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector_macro.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector_trait.hpp
/usr/include/mdds-1.2/mdds/multi_type_vector_types.hpp
/usr/include/mdds-1.2/mdds/node.hpp
/usr/include/mdds-1.2/mdds/point_quad_tree.hpp
/usr/include/mdds-1.2/mdds/quad_node.hpp
/usr/include/mdds-1.2/mdds/rectangle_set.hpp
/usr/include/mdds-1.2/mdds/rectangle_set_def.inl
/usr/include/mdds-1.2/mdds/segment_tree.hpp
/usr/include/mdds-1.2/mdds/segment_tree_def.inl
/usr/include/mdds-1.2/mdds/sorted_string_map.hpp
/usr/include/mdds-1.2/mdds/sorted_string_map_def.inl
/usr/include/mdds-1.2/mdds/trie_map.hpp
/usr/include/mdds-1.2/mdds/trie_map_def.inl
/usr/include/mdds-1.2/mdds/trie_map_itr.hpp
/usr/lib64/pkgconfig/mdds-1.2.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/mdds/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/mdds/COPYING
/usr/share/doc/mdds/LICENSE
