#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mdds
Version  : 1.5.0
Release  : 6
URL      : https://dev-www.libreoffice.org/src/mdds-1.5.0.tar.bz2
Source0  : https://dev-www.libreoffice.org/src/mdds-1.5.0.tar.bz2
Summary  : A collection of multi-dimensional data structure and indexing algorithm
Group    : Development/Tools
License  : MIT
Requires: mdds-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : dejagnu

%description
Multi-Dimensional Data Structure (mdds)
=======================================
A collection of multi-dimensional data structure and indexing
algorithm.

%package dev
Summary: dev components for the mdds package.
Group: Development
Provides: mdds-devel = %{version}-%{release}
Requires: mdds = %{version}-%{release}

%description dev
dev components for the mdds package.


%package doc
Summary: doc components for the mdds package.
Group: Documentation

%description doc
doc components for the mdds package.


%package license
Summary: license components for the mdds package.
Group: Default

%description license
license components for the mdds package.


%prep
%setup -q -n mdds-1.5.0
cd %{_builddir}/mdds-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580324205
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1580324205
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mdds
cp %{_builddir}/mdds-1.5.0/LICENSE %{buildroot}/usr/share/package-licenses/mdds/9b284bb2e965bb644bd7945b4198c55020a2714a
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mdds-1.5/mdds/flat_segment_tree.hpp
/usr/include/mdds-1.5/mdds/flat_segment_tree_def.inl
/usr/include/mdds-1.5/mdds/flat_segment_tree_itr.hpp
/usr/include/mdds-1.5/mdds/global.hpp
/usr/include/mdds-1.5/mdds/multi_type_matrix.hpp
/usr/include/mdds-1.5/mdds/multi_type_matrix_def.inl
/usr/include/mdds-1.5/mdds/multi_type_vector.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector/collection.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector/collection_def.inl
/usr/include/mdds-1.5/mdds/multi_type_vector_custom_func1.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector_custom_func2.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector_custom_func3.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector_def.inl
/usr/include/mdds-1.5/mdds/multi_type_vector_itr.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector_macro.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector_trait.hpp
/usr/include/mdds-1.5/mdds/multi_type_vector_types.hpp
/usr/include/mdds-1.5/mdds/node.hpp
/usr/include/mdds-1.5/mdds/point_quad_tree.hpp
/usr/include/mdds-1.5/mdds/quad_node.hpp
/usr/include/mdds-1.5/mdds/rectangle_set.hpp
/usr/include/mdds-1.5/mdds/rectangle_set_def.inl
/usr/include/mdds-1.5/mdds/rtree.hpp
/usr/include/mdds-1.5/mdds/rtree_def.inl
/usr/include/mdds-1.5/mdds/segment_tree.hpp
/usr/include/mdds-1.5/mdds/segment_tree_def.inl
/usr/include/mdds-1.5/mdds/sorted_string_map.hpp
/usr/include/mdds-1.5/mdds/sorted_string_map_def.inl
/usr/include/mdds-1.5/mdds/trie_map.hpp
/usr/include/mdds-1.5/mdds/trie_map_def.inl
/usr/include/mdds-1.5/mdds/trie_map_itr.hpp
/usr/lib64/pkgconfig/mdds-1.5.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/mdds/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mdds/9b284bb2e965bb644bd7945b4198c55020a2714a
